/**

  Motion LUTs of the selected robot

  - Copyright (C) 2024 - PRESENT  rookidroid.com
  - E-mail: info@rookidroid.com
  - Website: https://rookidroid.com/

  The LUTs themselves are generated by software/path_tool/generate_motion.py
  into src/robots/<name>/motion.h. Do not edit those by hand.

*/

#ifndef ROBOT_MOTION_H
#define ROBOT_MOTION_H

#include "robot.h"

#if defined(ROBOT_NOUGAT)
#include "src/robots/nougat/motion.h"
#elif defined(ROBOT_MOCHI)
#include "src/robots/mochi/motion.h"
#elif defined(ROBOT_MACAROON)
#include "src/robots/macaroon/motion.h"
#endif

#endif  // ROBOT_MOTION_H
