/**

  Geometry of the selected robot

  - Copyright (C) 2024 - PRESENT  rookidroid.com
  - E-mail: info@rookidroid.com
  - Website: https://rookidroid.com/

  The JSON itself is generated by software/path_tool/generate_motion.py into
  src/robots/<name>/robot_geometry.h. Do not edit those by hand.

*/

#ifndef ROBOT_GEOMETRY_SELECT_H
#define ROBOT_GEOMETRY_SELECT_H

#include "robot.h"

#if defined(ROBOT_NOUGAT)
#include "src/robots/nougat/robot_geometry.h"
#elif defined(ROBOT_MOCHI)
#include "src/robots/mochi/robot_geometry.h"
#elif defined(ROBOT_MACAROON)
#include "src/robots/macaroon/robot_geometry.h"
#endif

#endif  // ROBOT_GEOMETRY_SELECT_H
